"""initial migrate

Revision ID: 784d64289e5b
Revises: 
Create Date: 2022-03-11 17:50:18.668414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784d64289e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('idComm',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('idComm',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('storage',
    sa.Column('C1', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
